spring:
  application:
    name: to-do-app
  datasource:
    url: jdbc:mysql://database-2.cjeklvidjt6n.us-east-1.rds.amazonaws.com:3306/hr
    username: project
    password: project1234
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 5000  